spring:
  data:
    mongodb:
      username: admin
      password: admin
      database: DLAB
      port: 27017
      host: localhost
dlab:
  sbn: it78
  bigQueryDataset: test_dataset
  bigQueryTable: test
  cron: 0 * * * * *